function [radio] = helperGetRadioRxObj(ofdmRx)
%helperGetRadioTxObj(OFDMTX) returns the radio system object RADIO, based
%   on the chosen radio device and radio parameters such as Gain,
%   CentreFrequency, MasterClockRate, and Interpolation factor from the
%   radioParameter structure OFDMTX. The function additionally gives the
%   constellation diagram and spectrumAnalyzer system objects as output for
%   data visualizations

% Copyright 2023-2024 The MathWorks, Inc.

if strcmpi(ofdmRx.RadioDevice,'PLUTO')
    radio = sdrrx('Pluto');
    radio.BasebandSampleRate = ofdmRx.SampleRate;
    radio.CenterFrequency = ofdmRx.CenterFrequency;
    radio.SamplesPerFrame = ofdmRx.txWaveformSize;
    radio.OutputDataType = "double";
    radio.GainSource = "Manual";
    radio.Gain = ofdmRx.Gain;
    radio.EnableBurstMode = true;
    radio.NumFramesInBurst = ofdmRx.NumFrames+1;
else
    switch ofdmRx.RadioDevice
        case {'B200','B210'}
            radio = comm.SDRuReceiver(...
                'Platform',             ofdmRx.RadioDevice, ...
                'SerialNum',            ofdmRx.SerialNum, ...
                'ChannelMapping',       ofdmRx.channelmapping, ...
                'MasterClockRate',      ofdmRx.MasterClockRate, ...
                'CenterFrequency',      ofdmRx.CenterFrequency, ...
                'Gain',                 ofdmRx.Gain, ...
                'DecimationFactor',     ofdmRx.InterpDecim, ...
                'SamplesPerFrame',      ofdmRx.txWaveformSize, ...
                'OutputDataType',       'double',...
                'ClockSource',          'Internal',...
                'EnableBurstMode',      false,...
                'NumFramesInBurst',     ofdmRx.NumFrames+1);
        case {'N300','N310','N320/N321','N200/N210/USRP2','X300','X310'}
            radio = comm.SDRuReceiver(...
                'Platform',             ofdmRx.RadioDevice, ...
                'IPAddress',            ofdmRx.IPAddress, ...
                'ChannelMapping',       ofdmRx.channelmapping, ...
                'MasterClockRate',      ofdmRx.MasterClockRate, ...
                'CenterFrequency',      ofdmRx.CenterFrequency, ...
                'Gain',                 ofdmRx.Gain, ...
                'DecimationFactor',     ofdmRx.InterpDecim, ...
                'SamplesPerFrame',      ofdmRx.txWaveformSize, ...
                'OutputDataType',       'double', ...
                'EnableBurstMode',      false,...
                'NumFramesInBurst',     ofdmRx.NumFrames+1);
    end
end