function [radio, spectrumAnalyze, constDiag, timesink, constellation_measure] = helperGetRadioRxObj(ofdmRx)
%helperGetRadioTxObj(OFDMTX) returns the radio system object RADIO, based
%   on the chosen radio device and radio parameters such as Gain,
%   CentreFrequency, MasterClockRate, and Interpolation factor from the
%   radioParameter structure OFDMTX. The function additionally gives the
%   constellation diagram and spectrumAnalyzer system objects as output for
%   data visualizations

% Copyright 2023-2024 The MathWorks, Inc.

if strcmpi(ofdmRx.RadioDevice,'PLUTO')
    radio = sdrrx('Pluto');
    radio.BasebandSampleRate = ofdmRx.SampleRate;
    radio.CenterFrequency = ofdmRx.CenterFrequency;
    radio.SamplesPerFrame = ofdmRx.txWaveformSize;
    radio.OutputDataType = "double";
    radio.GainSource = "Manual";
    radio.Gain = ofdmRx.Gain;
    radio.EnableBurstMode = true;
    radio.NumFramesInBurst = ofdmRx.NumFrames+1;
else
    switch ofdmRx.RadioDevice
        case {'B200','B210'}
            radio = comm.SDRuReceiver(...
                'Platform',             ofdmRx.RadioDevice, ...
                'SerialNum',            ofdmRx.SerialNum, ...
                'ChannelMapping',       ofdmRx.channelmapping, ...
                'MasterClockRate',      ofdmRx.MasterClockRate, ...
                'CenterFrequency',      ofdmRx.CenterFrequency, ...
                'Gain',                 ofdmRx.Gain, ...
                'DecimationFactor',     ofdmRx.InterpDecim, ...
                'SamplesPerFrame',      ofdmRx.txWaveformSize, ...
                'OutputDataType',       'double',...
                'ClockSource',          'Internal',...
                'EnableBurstMode',      true,...
                'NumFramesInBurst',     ofdmRx.NumFrames+1);
        case {'N300','N310','N320/N321','N200/N210/USRP2','X300','X310'}
            radio = comm.SDRuReceiver(...
                'Platform',             ofdmRx.RadioDevice, ...
                'IPAddress',            ofdmRx.IPAddress, ...
                'ChannelMapping',       ofdmRx.channelmapping, ...
                'MasterClockRate',      ofdmRx.MasterClockRate, ...
                'CenterFrequency',      ofdmRx.CenterFrequency, ...
                'Gain',                 ofdmRx.Gain, ...
                'DecimationFactor',     ofdmRx.InterpDecim, ...
                'SamplesPerFrame',      ofdmRx.txWaveformSize, ...
                'OutputDataType',       'double', ...
                'EnableBurstMode',      true,...
                'NumFramesInBurst',     ofdmRx.NumFrames+1);
    end
end
% To visualize the constellation plot of the OFDM demodulated signal, you create
% a comm.ConstellationDiagram System object and set the ReferenceConstellation property
% to the generated reference constellations for header and data
% Set up constellation diagram object
refConstHeader = qammod(0:1,2,UnitAveragePower=true); % header is always BPSK
refConstData   = qammod(0:ofdmRx.modOrder-1,ofdmRx.modOrder,UnitAveragePower=true);
if ofdmRx.modOrder < 1024
constDiag = comm.ConstellationDiagram(2, ...
    "ChannelNames",{'Header','Data'}, ...
    "ReferenceConstellation",{refConstHeader,refConstData}, ...
    "ShowLegend",true, ...
    "EnableMeasurements",true, ...
    "MeasurementInterval",'All displays');
else
constDiag = comm.ConstellationDiagram(2, ...
    "ChannelNames",{'Header','Data'}, ...
    "ReferenceConstellation",{refConstHeader,refConstData}, ...
    "ShowLegend",true, ...
    "ShowReferenceConstellation", false, ...
    "EnableMeasurements",true, ...
    "MeasurementInterval",'All displays');
end

constellation_measure.mer_header = comm.MER("MeasurementIntervalSource", "Entire history", ...
    "ReferenceSignalSource","Estimated from reference constellation", ...
    "ReferenceConstellation",refConstHeader);
constellation_measure.mer_data = comm.MER("MeasurementIntervalSource", "Entire history", ...
    "ReferenceSignalSource","Estimated from reference constellation", ...
    "ReferenceConstellation",refConstData);

constellation_measure.evm_header = comm.EVM("MeasurementIntervalSource","Entire history", ...
    "ReferenceSignalSource","Estimated from reference constellation", ...
    "ReferenceConstellation",refConstHeader);
constellation_measure.evm_data = comm.EVM("MeasurementIntervalSource","Entire history", ...
    "ReferenceSignalSource","Estimated from reference constellation", ...
    "ReferenceConstellation",refConstData);


% Additionally, initialize the spectrumAnalyzer System object in-order to
% visualize the received waveform.
spectrumAnalyze = spectrumAnalyzer( ...
    'Name',             'Signal Spectrum', ...
    'Title',            'Received Signal', ...
    'SpectrumType',     'Power', ...
    'FrequencySpan',    'Full', ...
    'SampleRate',       ofdmRx.SampleRate, ...
    'ShowLegend',       true, ...
    'ViewType',         'spectrum-and-spectrogram', ...
    'Position',         [100 100 800 500], ...
    'ChannelNames',     {'Received'});

timesink = timescope( ...
    Name='Time Scope', ...
    Title='received signal', ...
    ChannelNames={'(real) original time-domain data', '(real) processed(cfo) time-domain data', '(imag) original time-domain data',  '(imag) processed(cfo) time-domain data'}, ...
    ShowLegend=true, ...
    SampleRate=ofdmRx.SampleRate, ...
    YLimits=[-0.4,0.4], ...
    LayoutDimensions=[2,1], ...
    ActiveDisplay=2);
end