function [visualizationTools] = setupVisualizationTools(sysParamRxObj)
    % setupVisualizationTools: Set up visualization tools (constellation diagram,
    % EVM, MER, spectrum analyzer, and time scope) for all BSs using sysParamRxObj.
    %
    % Input:
    %   sysParamRxObj - Structure containing system parameters and receiver objects for each BS
    %
    % Output:
    %   visualizationTools - Structure containing all visualization tools for each BS

    % 获取 sysParamRxObj 中所有基站的 field names
    BS_fieldnames = fieldnames(sysParamRxObj);

    % 初始化保存所有基站可视化工具的结构体
    visualizationTools = struct();

    % 遍历所有在线基站，分别为每个基站配置工具
    for index = 1:length(BS_fieldnames)
        % 获取当前基站的 fieldname (e.g., 'BS_1', 'BS_2')
        current_BS_field = BS_fieldnames{index};

        % 从 sysParamRxObj 中提取相关参数
        OFDMParams = sysParamRxObj.(current_BS_field).OFDMParams;
        dataParams = sysParamRxObj.(current_BS_field).dataParams;
        
        % 根据基站的modOrder和采样率生成星座图参考点
        refConstHeader = qammod(0:1, 2, UnitAveragePower=true);  % Header is always BPSK
        refConstData   = qammod(0:dataParams.modOrder-1, dataParams.modOrder, UnitAveragePower=true);
        
        % 初始化星座图
        if dataParams.modOrder < 1024
            constDiag = comm.ConstellationDiagram(2, ...
                "ChannelNames", {'Header','Data'}, ...
                "ReferenceConstellation", {refConstHeader, refConstData}, ...
                "ShowLegend", true, ...
                "EnableMeasurements", true, ...
                "MeasurementInterval", 'All displays', ...
                "Title", current_BS_field + " Constellation Diagram");
        else
            constDiag = comm.ConstellationDiagram(2, ...
                "ChannelNames", {'Header','Data'}, ...
                "ReferenceConstellation", {refConstHeader, refConstData}, ...
                "ShowLegend", true, ...
                "ShowReferenceConstellation", false, ...
                "EnableMeasurements", true, ...
                "MeasurementInterval", 'All displays', ...
                "Title", current_BS_field + " Constellation Diagram");
        end
        
        %%%%%%%%%%%%%%%%%%%%%%%%% 这里有一些可选项 %%%%%%%%%%%%%%%%%%%%%%%%%
        constDiag.ShowTrajectory = false;
        %%%%%%%%%%%%%%%%%%%%%%%%% 这里有一些可选项 %%%%%%%%%%%%%%%%%%%%%%%%%

        % 初始化EVM和MER测量对象
        constellation_measure.mer_header = comm.MER(...
            "MeasurementIntervalSource", "Entire history", ...
            "ReferenceSignalSource", "Estimated from reference constellation", ...
            "ReferenceConstellation", refConstHeader);
        
        constellation_measure.mer_data = comm.MER(...
            "MeasurementIntervalSource", "Entire history", ...
            "ReferenceSignalSource", "Estimated from reference constellation", ...
            "ReferenceConstellation", refConstData);
        
        constellation_measure.evm_header = comm.EVM(...
            "MeasurementIntervalSource", "Entire history", ...
            "ReferenceSignalSource", "Estimated from reference constellation", ...
            "ReferenceConstellation", refConstHeader);
        
        constellation_measure.evm_data = comm.EVM(...
            "MeasurementIntervalSource", "Entire history", ...
            "ReferenceSignalSource", "Estimated from reference constellation", ...
            "ReferenceConstellation", refConstData);
        
        % 初始化频谱分析仪
        spectrumAnalyze = spectrumAnalyzer( ...
            'Name',             'Signal Spectrum', ...
            'Title',            ['Received Signal (' current_BS_field ')'], ...
            'SpectrumType',     'Power', ...
            'FrequencySpan',    'Full', ...
            'SampleRate',       OFDMParams.Subcarrierspacing * OFDMParams.FFTLength, ...
            'ShowLegend',       true, ...
            'ViewType',         'spectrum-and-spectrogram', ...
            'Position',         [100 100 800 500], ...
            'ChannelNames',     {'Received'});
        
        % 初始化时间域图
        timesink = timescope( ...
            'Name',             'Time Scope', ...
            'Title',            ['Received Signal (' current_BS_field ')'], ...
            'ChannelNames',     {'(real) original time-domain data', ...
                                 '(real) processed(cfo) time-domain data', ...
                                 '(imag) original time-domain data', ...
                                 '(imag) processed(cfo) time-domain data'}, ...
            'ShowLegend',       true, ...
            'SampleRate',       OFDMParams.Subcarrierspacing * OFDMParams.FFTLength, ...
            'YLimits',          [-0.4, 0.4], ...
            'LayoutDimensions', [2, 1], ...
            'ActiveDisplay',    2);

        % 将每个基站的工具保存到结构体中
        visualizationTools.(current_BS_field).constDiag = constDiag;
        visualizationTools.(current_BS_field).constellation_measure = constellation_measure;
        visualizationTools.(current_BS_field).spectrumAnalyze = spectrumAnalyze;
        visualizationTools.(current_BS_field).timesink = timesink;
    end
end
